**numpy, array, matrix**

In [1]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

creating arrays

In [4]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(4.0)

array([0., 1., 2., 3.])

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [13]:
np.arange(20,10)

array([], dtype=int32)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [16]:
np.arange(30,20)  # frist argument always < second argument

array([], dtype=int32)

In [17]:
np.arange(-30,30)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,
        22,  23,  24,  25,  26,  27,  28,  29])

In [18]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [19]:
np.arange(10,30,5) # 10- starting from ||  30 -end point ||  5- step count 

array([10, 15, 20, 25])

In [20]:
np.arange(100,500,3)

array([100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136,
       139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172, 175,
       178, 181, 184, 187, 190, 193, 196, 199, 202, 205, 208, 211, 214,
       217, 220, 223, 226, 229, 232, 235, 238, 241, 244, 247, 250, 253,
       256, 259, 262, 265, 268, 271, 274, 277, 280, 283, 286, 289, 292,
       295, 298, 301, 304, 307, 310, 313, 316, 319, 322, 325, 328, 331,
       334, 337, 340, 343, 346, 349, 352, 355, 358, 361, 364, 367, 370,
       373, 376, 379, 382, 385, 388, 391, 394, 397, 400, 403, 406, 409,
       412, 415, 418, 421, 424, 427, 430, 433, 436, 439, 442, 445, 448,
       451, 454, 457, 460, 463, 466, 469, 472, 475, 478, 481, 484, 487,
       490, 493, 496, 499])

In [21]:
np.arange(10,100,5.5)

array([10. , 15.5, 21. , 26.5, 32. , 37.5, 43. , 48.5, 54. , 59.5, 65. ,
       70.5, 76. , 81.5, 87. , 92.5, 98. ])

In [22]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.arange(0,20,2,1)

TypeError: Cannot interpret '1' as a data type

In [24]:
b1 = np.zeros(2)   # parameter tunning
b1

array([0., 0.])

In [25]:
np.zeros(5 ,dtype=int)

array([0, 0, 0, 0, 0])

In [26]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [31]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
n=(5,7)
n1=(6,8)
print(np.zeros(n))   #parameter tunning 
#print np.zeros(n1,dtype =int)  # hyperparameter tunning 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [33]:
np.zeros(n1,dtype = int) # hyper parameter tunning 

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [38]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
n

(5, 7)

In [40]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.ones((5,4),dtype=int)  #by default 5- rows and 4- columns 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
np.twos(2,4)

AttributeError: module 'numpy' has no attribute 'twos'

In [43]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [45]:
np.three((2,4))


AttributeError: module 'numpy' has no attribute 'three'

In [46]:
np.arange(3)

array([0, 1, 2])

In [47]:
from numpy import * #intarnally is called all 217 functionality 
arange(3)

array([0, 1, 2])

In [48]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [49]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [50]:
from numpy import *
zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [52]:
np.random.rand(5)

array([0.88264494, 0.73485007, 0.03665707, 0.72906118, 0.75054876])

In [53]:
np.random.rand(2,5)

array([[0.32351075, 0.03919587, 0.66900894, 0.9208729 , 0.66322917],
       [0.1203259 , 0.07556259, 0.74695781, 0.22650772, 0.22383365]])

In [54]:
np.random.randint(3,20) # 2nd argument is excludsive 

10

In [55]:
np.random.randint(0,2)

0

In [56]:
np.random.randint(1,10,4)

array([5, 3, 3, 3])

In [57]:
np.random.randint(30,20,10)

ValueError: low >= high

In [58]:
np.random.randint(5,9) #get the value <=9 & >=5

5

In [59]:
np.random.randint(10,21,3)

array([13, 20, 11])

In [60]:
np.random.randint(10,40,(10,10)) # generate the element 10-40 with 4*4
# generating array 10x10  in between 10-40

array([[32, 23, 20, 33, 13, 12, 17, 24, 27, 24],
       [15, 10, 36, 14, 27, 39, 26, 32, 31, 29],
       [27, 28, 32, 30, 31, 25, 18, 19, 35, 15],
       [36, 23, 16, 33, 15, 34, 32, 15, 38, 20],
       [23, 17, 37, 21, 23, 35, 27, 37, 12, 22],
       [16, 37, 14, 34, 13, 16, 32, 20, 18, 30],
       [24, 25, 23, 13, 18, 21, 36, 12, 34, 24],
       [35, 30, 13, 20, 24, 29, 16, 31, 33, 14],
       [25, 36, 27, 12, 22, 38, 31, 28, 23, 24],
       [26, 19, 16, 27, 23, 21, 32, 15, 29, 16]])

In [61]:
b=np.random.randint(10,20,(5,4))  # 5x4 array in between numbers 10-20
b

array([[19, 16, 14, 10],
       [10, 17, 17, 12],
       [11, 14, 13, 13],
       [11, 18, 14, 18],
       [14, 14, 10, 15]])

In [62]:
b[:]

array([[19, 16, 14, 10],
       [10, 17, 17, 12],
       [11, 14, 13, 13],
       [11, 18, 14, 18],
       [14, 14, 10, 15]])

In [63]:
b[0:2] # slicing [ start : stop : step]

array([[19, 16, 14, 10],
       [10, 17, 17, 12]])

In [64]:
b

array([[19, 16, 14, 10],
       [10, 17, 17, 12],
       [11, 14, 13, 13],
       [11, 18, 14, 18],
       [14, 14, 10, 15]])

In [65]:
b[0,2]

14

In [66]:
b[0:-1]

array([[19, 16, 14, 10],
       [10, 17, 17, 12],
       [11, 14, 13, 13],
       [11, 18, 14, 18]])

In [67]:
b

array([[19, 16, 14, 10],
       [10, 17, 17, 12],
       [11, 14, 13, 13],
       [11, 18, 14, 18],
       [14, 14, 10, 15]])

In [68]:
np.random.randint(10,20,(4,4))

array([[11, 17, 14, 19],
       [16, 15, 11, 19],
       [17, 13, 11, 18],
       [11, 13, 14, 17]])

operations

In [69]:
a = np.random.randint(10,20,5)
a

array([15, 12, 15, 10, 14])

In [70]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[68, 68, 43, 94,  3,  7, 97,  8, 40,  5],
       [27,  2, 40, 86, 85, 71, 85, 84, 10, 69],
       [92, 20, 16, 26, 87, 95, 32, 97, 62, 23],
       [97, 60, 81, 77, 13, 69, 11, 48,  5, 51],
       [60, 30, 82, 49, 39,  9, 29,  8, 90, 49],
       [34, 93, 25, 34, 41, 67, 27,  4, 29,  5],
       [11, 66, 28, 33, 45, 18, 62, 36, 33, 25],
       [55, 15, 32, 50, 31, 73, 96, 21, 52, 70],
       [87, 11, 25, 55, 25,  3, 26, 10, 95, 14],
       [84, 21, 40, 91, 28, 11, 72, 35, 63, 47]])

In [71]:
arr

array([0, 1, 2, 3, 4, 5])

In [72]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [73]:
arr[:4]

array([0, 1, 2, 3])

In [74]:
arr2[:]

array([[68, 68, 43, 94,  3,  7, 97,  8, 40,  5],
       [27,  2, 40, 86, 85, 71, 85, 84, 10, 69],
       [92, 20, 16, 26, 87, 95, 32, 97, 62, 23],
       [97, 60, 81, 77, 13, 69, 11, 48,  5, 51],
       [60, 30, 82, 49, 39,  9, 29,  8, 90, 49],
       [34, 93, 25, 34, 41, 67, 27,  4, 29,  5],
       [11, 66, 28, 33, 45, 18, 62, 36, 33, 25],
       [55, 15, 32, 50, 31, 73, 96, 21, 52, 70],
       [87, 11, 25, 55, 25,  3, 26, 10, 95, 14],
       [84, 21, 40, 91, 28, 11, 72, 35, 63, 47]])

In [75]:
arr2[1,5]

71

In [76]:
arr2[-5,5]

67

In [77]:
arr2[-1,2]

40

In [78]:
arr2[::-1]

array([[84, 21, 40, 91, 28, 11, 72, 35, 63, 47],
       [87, 11, 25, 55, 25,  3, 26, 10, 95, 14],
       [55, 15, 32, 50, 31, 73, 96, 21, 52, 70],
       [11, 66, 28, 33, 45, 18, 62, 36, 33, 25],
       [34, 93, 25, 34, 41, 67, 27,  4, 29,  5],
       [60, 30, 82, 49, 39,  9, 29,  8, 90, 49],
       [97, 60, 81, 77, 13, 69, 11, 48,  5, 51],
       [92, 20, 16, 26, 87, 95, 32, 97, 62, 23],
       [27,  2, 40, 86, 85, 71, 85, 84, 10, 69],
       [68, 68, 43, 94,  3,  7, 97,  8, 40,  5]])

In [79]:
arr2

array([[68, 68, 43, 94,  3,  7, 97,  8, 40,  5],
       [27,  2, 40, 86, 85, 71, 85, 84, 10, 69],
       [92, 20, 16, 26, 87, 95, 32, 97, 62, 23],
       [97, 60, 81, 77, 13, 69, 11, 48,  5, 51],
       [60, 30, 82, 49, 39,  9, 29,  8, 90, 49],
       [34, 93, 25, 34, 41, 67, 27,  4, 29,  5],
       [11, 66, 28, 33, 45, 18, 62, 36, 33, 25],
       [55, 15, 32, 50, 31, 73, 96, 21, 52, 70],
       [87, 11, 25, 55, 25,  3, 26, 10, 95, 14],
       [84, 21, 40, 91, 28, 11, 72, 35, 63, 47]])

In [80]:
arr2[::-2]

array([[84, 21, 40, 91, 28, 11, 72, 35, 63, 47],
       [55, 15, 32, 50, 31, 73, 96, 21, 52, 70],
       [34, 93, 25, 34, 41, 67, 27,  4, 29,  5],
       [97, 60, 81, 77, 13, 69, 11, 48,  5, 51],
       [27,  2, 40, 86, 85, 71, 85, 84, 10, 69]])

In [81]:
arr2[::-3]

array([[84, 21, 40, 91, 28, 11, 72, 35, 63, 47],
       [11, 66, 28, 33, 45, 18, 62, 36, 33, 25],
       [97, 60, 81, 77, 13, 69, 11, 48,  5, 51],
       [68, 68, 43, 94,  3,  7, 97,  8, 40,  5]])

In [82]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
arr.max()

5

In [84]:
arr.min()

0

In [85]:
arr.mean()

2.5

In [86]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [87]:
from numpy import *
a= array([1,2,3,4,9])
median(a)

3.0

In [88]:
arr

array([0, 1, 2, 3, 4, 5])

In [89]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [91]:
arr

array([0, 1, 2, 3, 4, 5])

In [92]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [93]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [94]:
arr.reshape(3,2,order='A')


array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
arr.reshape(3,2,order='k')

ValueError: order 'K' is not permitted for reshaping

In [96]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [97]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

**indexing**

In [98]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
row = 4
col = 5

In [100]:
print(row)
print(col)

4
5


In [101]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[row,col]

45

In [103]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
col=6 # this will be use to specify column to extract 

In [105]:
# with slices 
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [106]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [107]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [108]:
row

4

In [109]:
mat[:col] # this slice extract frist 6 columns 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [110]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [111]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
mat[row:]

In [ ]:
mat

In [ ]:
mat[:,8]

In [ ]:
mat[:8]

In [ ]:
mat[:,-1]

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [ ]:
mat[1,4]

In [ ]:
mat[1:4]

In [ ]:
mat

In [ ]:
mat[3:-3]

In [ ]:
mat[0]

In [ ]:
mat[6]

In [ ]:
mat[6:] # print from 60 to end.

In [ ]:
mat[5:7]

In [ ]:
mat

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat[::-2]

In [ ]:
mat[::-3]

In [ ]:
mat[::-5]

In [ ]:
mat

In [ ]:
mat[2:6]

In [ ]:
mat[2:6,2:4] #--->>. only row part /// 1:3--- indicates only column parts

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat[3:5]

In [ ]:
mat

In [ ]:
mat[1:2,2:4] # it shoud be 12 and 13

In [ ]:
mat[2:3,2:3]

In [ ]:
mat[3:5,2:4]

In [ ]:
mat[2:3,4:5]

**masking**

In [ ]:
mat #we also called as filter

In [ ]:
id(mat)

In [ ]:
mat

In [ ]:
mat < 50

In [ ]:
mat > 50

In [ ]:
mat == 50

In [ ]:
mat[mat==50]

In [ ]:
array([50])

In [ ]:
a1 = mat[mat<50]
a1

In [ ]:
mat

In [ ]:
a2=mat[mat>50]
a2

In [ ]:
a3=mat[mat>=50]
a3

In [ ]:
a1

In [ ]:
a2